### ISSUE TITLE
How to change colors, fonts, font-size, etc.?

### ISSUE THREAD

**Issue by mrticker** [getcursor/cursor#103]
^

**Comment by truell20** [comment]
Hey! Which of the colors and fonts bother you the most right now? Is this all in the editor itself? What would your designed theming look like?

**Comment by 422949495** [comment]
I want to change the background color to white

**Comment by Jussick** [comment]
> Hey! Which of the colors and fonts bother you the most right now? Is this all in the editor itself? What would your designed theming look like?

I think he wants to say that as a code editor, it should be able to change the color and font freely. Albeit I don't think it is the highest priority for the dev team, because the team has more important features to develop for now. However you could consider to add Black and White theme，that's a little easier relatively.

**Comment by mrticker** [comment]
^
I'd prefer a light theme, although not necessarily with a white background. I would also like to be able to adjust font size.

**Comment by truell20** [comment]
Newest version should allow you to customize all you want 🙂
