### ISSUE TITLE
cursor did not use the latest code  for modifications？

### ISSUE THREAD

**Issue by lutixiaya** [getcursor/cursor#110]
After cursor provided a code block A according to a requirement, it made modifications to A and obtained a new code block B. If further modifications were made to B, cursor did not base its modifications on B, but rather on the original code block A. In other words, cursor did not use the latest code block B for modifications.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/48750425/226241635-6a8dd2f4-f2bb-4b19-ade5-4ca59e8b10f9.png">

<img width="397" alt="image" src="https://user-images.githubusercontent.com/48750425/226241689-ecfe1ee6-35ee-4d66-8a6b-16bdc3df8896.png">

**Comment by danperks** [comment]
It's possible that you still had the original code highlighted, which suggested to the AI that was the latest version of the code you wanted to discuss with it. In your prompts, make sure to tell the AI you tried it's last suggestion, and what happened, to give it a better idea of the context of your question. Since your issue, Cursor v0.2.0 and up features some significant changes, so I'd recommend giving that a try, and creating a new issue if you have any issues you'd like addressing. 😄
