### ISSUE TITLE
Can't `/edit` if using own OpenAI API key.

### ISSUE THREAD

**Issue by bluet** [getcursor/cursor#1120]
1) If you can, please include a screenshot of your problem

   - I've set my OpenAI API key successfully. I can ask questions, and it does answer.
   - But it refused to work when I asked it to edit files.
   ```
   API key not supported.
   The /edit feature uses non-public models and cannot be accessed by API key.
   ```

   Curious: since when only paying users can use `/edit` feature?
   Is there any subscription plan for Cursor Editor that allows me to use my OpenAI API key and pay less for the subscription- only feature?

![螢幕快照 2023-12-08 16-23-14](https://github.com/getcursor/cursor/assets/51141/af02413b-0706-4382-acab-46b0722872a0)
![螢幕快照 2023-12-08 16-13-41](https://github.com/getcursor/cursor/assets/51141/f400575c-bd97-4b59-b728-bff30851b90c)

2) Please include the name of your operating system

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

3) If you can, steps to reproduce are super helpful

   1. Set OpenAI API key into Cursor Editor
   2. Open a code project
   3. Ask something
   4. Click "Apply to Current File"
   5. It refuses to edit and says it does not support it.

**Comment by yuyu82** [comment]
This event also occurs in my environment when using openai's api.

**Comment by jakobFNF** [comment]
It’s intended because /edit uses non-public models and therefore can’t be used by your own OpenAI API Key. You have to use Cursor’s own GPT-4 requests for it.

**Comment by rairulyle** [comment]
@jakobFNF if this is intended, then is there a way to show in the UI that this is only available if we are using Cursor's API?

**Comment by AncalagonX** [comment]
@jakobFNF @rairulyle I would like a hybrid approach: to be able to use my own OpenAI API Key for all normal requests except the "Apply to current file" `/edit` feature.

I have a Cursor.sh paid account which I hardly use and will probably cancel because it's more convenient to use my own API key. However, the `/edit` feature is so good that I'd keep a paid account if it could be used while I've got my API key active. I wish there was a middle ground here.
