### ISSUE TITLE
changelog.cursor.sh is not updated

### ISSUE THREAD

**Issue by gsusI** [getcursor/cursor#1187]
changelog.cursor.sh:

![image](https://github.com/getcursor/cursor/assets/4558016/65e03053-69ab-4dc7-86dc-2d26f29d1b5b)

Cursor's "Help: About":

![image](https://github.com/getcursor/cursor/assets/4558016/ea8fa614-9515-4875-9656-8a65e1c63c8c)

**Comment by truell20** [comment]
Noted! We will be better about updating the changelog for patches.

**Comment by s1awek** [comment]
Hi, there are still no new updates visible on https://www.cursor.com/changelog - I have probably had about 2 updates already (current version is 0.46.2), but the changelog still shows version 0.45. Also, even if there is an update, it is often very broad, e.g. 

`UPDATE (0.45.12-13): Update infrastructure improvements. The F1 > "Check for Updates" command should now work.`

For me as a user, this is important information because I want to test it myself instead of being surprised by these changes during coding.
