### ISSUE TITLE
[Feature Request] Launch from the command line

### ISSUE THREAD

**Issue by photkey** [getcursor/cursor#121]
You want to support launching from the command line with the parameters: -d: folder, -f which file to open

If this is supported, you can use Cursor.exe to quickly open the project directory from any location and locate the file to edit

For example: Cursor -d D:\Folder -f D:\Folder\dir\File.py, you can quickly open the folder Folder and locate the file /dir/File.py

To give a practical example, let's say I'm editing a script in VSCode, I can pass these parameters by editing a command and then assign a shortcut to seamlessly switch from vscode to Cursor to continue editing with one click

Translated with www.DeepL.com/Translator (free version)

**Comment by truell20** [comment]
Should be able to use `cursor` command from the command line in the newest version

To install this hook, use command + shift + p to pull up the command palette and then search for something like 'Install command in path'

**Comment by R3flector** [comment]
![image](https://github.com/getcursor/cursor/assets/58531356/91304d19-73c9-4804-8278-c8819def18f2)

no such option

**Comment by ChenBingWei1201** [comment]
I am also unable to install the command line `cursor`.
platform info:
cursor version:  `0.20.2.AppImage`
OS: `ubuntu 22.04`
<img src="https://github.com/getcursor/cursor/assets/49435609/b9f21232-7e37-4d6a-ba62-584b8f559725" width="500"/>

**Comment by beduffy** [comment]
I have this same problem

**Comment by Haraven** [comment]
I had the same issue. 

As a workaround, I edited my shell's config file and added a line like below:

`alias cursor="PATH/TO/CURSOR.appimage"`

After reloading the shell, I can open files and folders in Cursor from the command line.

**Comment by kashif-ghafoor** [comment]
> I had the same issue.
> 
> As a workaround, I edited my shell's config file and added a line like below:
> 
> `alias cursor="PATH/TO/CURSOR.appimage"`
> 
> After reloading the shell, I can open files and folders in Cursor from the command line.

after update the name of CURSOR.appimage usually get changed with the change in version.

**Comment by Haraven** [comment]
> > I had the same issue.
> > As a workaround, I edited my shell's config file and added a line like below:
> > `alias cursor="PATH/TO/CURSOR.appimage"`
> > After reloading the shell, I can open files and folders in Cursor from the command line.
> 
> after update the name of CURSOR.appimage usually get changed according to newer version.

Good point. Another workaround would be to search for the cursor appimage name in its installed folder.

For fish, this would be:
```fish
set cursor_path (find PATH/TO/CURSOR_DIR/ -type f | grep -E "/cursor-.*\.[Aa]pp[Ii]mage")
alias cursor=$cursor_path
```

For other shells, the commands are the same, you just need to change the syntax for assigning `cursor_path`.

The first line will list all files in the Cursor directory and then it will filter those files so that only those that have a name like `cursor-SOME VERSION INFORMATION.AppImage` remain. Assuming you only have 1 file that has that kind of name in your Cursor directory, and assuming the Cursor naming convention doesn't change, this should correctly detect any Cursor version.

**Comment by Haraven** [comment]
**Update**: I switched  from AppImageLauncher to Gear Lever and as a consequence I had to update the regex I posted earlier in this issue. This is because Gear Lever has slightly different naming conventions by default. 

Here is an updated version of my fish config script, which works with both AppImageLauncher and Gear Lever:
```fish
set cursor_path (find /home/shelomoh/Applications/ -type f | grep -E '/(gearlever_)?cursor(-|_).*\.[Aa]pp[Ii]mage$')
alias cursor=$cursor_path
```

**Comment by fonnesbeck** [comment]
For bash, the following works with a GearLever installation:

```bash
alias cursor=$(find $HOME/AppImages -type f | grep -E '/(gearlever_)?cursor(-|_).*\.[Aa]pp[Ii]m
age$')
```
