### ISSUE TITLE
请问会支持插件么？比如VisualStudio或IDEA的插件

### ISSUE THREAD

**Issue by obeyconquer** [getcursor/cursor#150]
请问会支持插件么？比如VisualStudio或IDEA的插件
在工作中时可能会需要一些插件的支持，但是在产品中并未找到对应的支持，不知道是没有还是我未找到。

**Comment by danperks** [comment]
While I can only comment in English in return, I translated your question. Cursor is, and likely always will be, a standalone editor. According to the developers, there are no plans to implement any Cursor features into any other IDEs, due to the limitations those IDEs cause. Instead, the goal is to implement many of the best features of the IDEs into Cursor over time!

**Comment by truell20** [comment]
@obeyconquer in our opinion, programming in the future will consist largely of interacting with llms. we think this requires a whole new editor 🙂
