### ISSUE TITLE
The @web doesnt look for youtube videos or reddit posts

### ISSUE THREAD

**Issue by Am0stafa** [getcursor/cursor#1846]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by danperks** [comment]
The @web function is purely for web content, and does not support video inputs. The web scraping likely occurs on Cursor's (or the LLM providers) servers, and will be tuned to get the best accuracy of results, which may include excluding Reddit pages. This is probably done for a reason, and therefore likely won't be changed. Video support is even more unlikely due to the workload required to transcribe a video into information an LLM can understand.
