### ISSUE TITLE
is not  gpt4

### ISSUE THREAD

**Issue by 767472021** [getcursor/cursor#204]
![image](https://user-images.githubusercontent.com/19233945/227411525-08303071-9a3e-4a59-bb46-cce5546de989.png)

**Comment by truell20** [comment]
hey! even if you ask gpt-4 if it's gpt-4, it won't actually know because of how it's trained.

that said, we now use gpt-3.5 a ton because of the cost of running four (see discord faqs)

<img width="640" alt="Screenshot 2023-03-24 at 3 17 44 PM" src="https://user-images.githubusercontent.com/4297743/227653499-658ea598-4b26-4980-81b8-8a5b3345bf94.png">
