### ISSUE TITLE
Cursor: Open Edit (Command K) shortcut conflicts with VS Code Delete Line

### ISSUE THREAD

**Issue by nhuxhr** [getcursor/cursor#2186]
## Description

The current shortcut for **Cursor: Open Edit (Command K)** using `ctrl+shift+k` conflicts with the default VS Code shortcut for **Delete Line**. This creates confusion and inconsistency for users who are familiar with VS Code's default keybindings.

## Steps to reproduce

1. Open Cursor
2. Attempt to use `ctrl+shift+k` to delete a line
3. Observe that Cursor Composer opens instead of deleting the line

## Expected behavior

`ctrl+shift+k` should perform the default VS Code "Delete Line" action.

## Actual behavior

`ctrl+shift+k` opens the Cursor Composer.

## Proposed solution

Consider changing the default shortcut for **Cursor: Open Edit (Command K)** to a different key combination that doesn't conflict with common VS Code shortcuts.

## Additional notes

This issue affects user productivity and workflow, especially for those who frequently use the **Delete Line** feature in VS Code and expect the same functionality in Cursor.

**Comment by danperks** [comment]
As you probably know, there are a lot of keyboard shortcuts available in the default VSCode installation, and adding Cursor's AI features only increases that list's size. Therefore, a collision like this was likely inevitable.

As most people get Cursor for the AI features it offers, such as the Composer, those shortcuts would likely take priority as default now, since many people will be used to CTRL+SHIFT+K as the shortcut for Composer. While I get that this is a collision for VSCode users, it's probably too late to change it now, at risk of throwing off existing users. 

The beauty of both VSCode and Cursor is that you have the flexibility to change either shortcut to something different if you choose. As the time to resolve this is low, and has trade-offs either way, my guess is your proposed solution wouldn't be implemented as the default.

In an effort to try clean up the issues on this repo, I'll close this for now, but feel free to comment back and I'll reopen it if something more comes of the discussion. Thanks for the suggestion regardless!

**Comment by alflennik** [comment]
Would it be possible to assign delete line to some other keyboard shortcut then?

**Comment by alysakowski** [comment]
I was also struggling but found solution, if you will go to preferences and settings you can change `CMD + Shift + K` to `CMD + K ` it will unlock default VSCode delete line which is this taken `CMD + Shift + K`

**Comment by RickeyWard** [comment]
The idea that this keyboard shortcut is double bound, one for toggle and one for open, and then overrides one of the most commonly used keyboard shortcuts in programming is a very odd design decision. Please reconsider this.

**Comment by davnicwil** [comment]
As of right now (v0.50.4) the situation has got a bit stranger. These are the defaults:

`CMD+K` => inline AI edit
`CMD+Shift+K` => _file level_ AI edit
`CMD+I` => full chat in sidebar

Weirdly, despite these changes delete line is _still_ auto-bound to `CMD+Shift+K` and just doesn't work.

To solve I rebound delete line to `CMD+Ctrl+K` which has no conflict. Works well enough for me and only a slight re-learning.

**Comment by brianlegault16** [comment]
Hey @danperks,

Cmd + k is also the first command in a whole pile of compound shortcuts (Eg. `cmd + k z `for Zen mode). So Cursor has chosen the most impactful command to override and not document what it was replaced with. If a user wants to change their keybindings back to VS Code defaults, they have dozens of commands to change (if they need them all).... They can't just override/update the `cmd + k` and `cmd + shift + k`.

For anyone wondering, `shift + cmd + p`, then type "Open Default Keyboard shortcuts" to see that they moved all `cmd + k` compound commands to `cmd + r`. Their docs don't mention that, that I could find.

Hoping this decision is reconsidered.

**Comment by wonder-wanderer** [comment]
For everyone, i found that o**n PC now ctr+K is changed into ctrl+M**, and ctrl+R remains open recent as in VSCode. But it wasn't in the docs https://docs.cursor.com/kbd So @brianlegault16 thanks a lot mate, you guided me! 

My comment to Cursor creators: ctrl + k compound shourtcut is "the most" (or at least on of THE most) important shortcut of VSCode, so it is beyond my comprehension how could someone take actual VSCode and override it, and if even if someone would, then how that someone could not relate to that fact and provide right into my face really loud and clear instructions of what to do. Such a shame. Apart from that good product, but why such annoyance in most basic stuff.
