### ISSUE TITLE
Dev Container with OrbStack fails to open

### ISSUE THREAD

**Issue by maxritter** [getcursor/cursor#2199]
I recently switched from Docker Desktop to OrbStack on my Macbook Pro M3. The Dev Container still works fine in the latest version of VS Code, but in Cursor it fails to open with this error message:

<img width="1080" alt="Screenshot 2024-10-07 at 08 24 56" src="https://github.com/user-attachments/assets/4e23403f-afbd-48de-90d7-82a1e2da9078">

OrbStack is running and there is no issue within VS Code, so the problem is related to Cursor.

**Comment by danperks** [comment]
Issues relating to `docker.sock` not being visible to an app is usually due to the permissions now allowing it.

Try running Cursor from the terminal with `sudo`, as it should then be able to access the `docker.sock` daemon.
If that works, we can figure out what VSCode is doing that Cursor to cause it to not work out the box.

**Comment by maxritter** [comment]
@danperks I launched Cursor with sudo but the issue is still the same..

**Comment by danperks** [comment]
It may be that this relies on an extensions that is more up to date in VSCode than Cursor can support.

What do you get in the terminal if you run "docker version"?

**Comment by maxritter** [comment]
@danperks The issue was on my side, I was using a quicklink from Launchpad that pointed to the Docker Desktop version of the Dev Container. When I opened the container over the dialog menu it was able to create the orbstack link fine. Sorry for the inconvenience!

**Comment by danperks** [comment]
Ah no worries, glad you figured it out :)
