### ISSUE TITLE
Error connecting to unsupported large model vendors using llitellm

### ISSUE THREAD

**Issue by wuming123** [getcursor/cursor#2351]
![image](https://github.com/user-attachments/assets/537d3179-1b3e-49ae-800a-3d15bc73aced)
![image](https://github.com/user-attachments/assets/0294a675-e3d7-418e-9187-efa64b5112c9)

It can be validated fine, but it's not possible to talk and edit the code, I don't understand why

![image](https://github.com/user-attachments/assets/973966c9-3944-4a29-a36f-cbbfe6add55e)

When I find that it reports this error when I do a chat, no network request has occurred, so I'm assuming it's an error in validating some local data?
![image](https://github.com/user-attachments/assets/9b73a9cd-3f5a-4840-9b1b-1b8b51482c39)

Looking forward to your replies and solutions, thanks!

**Comment by danperks** [comment]
Hi @wuming123,

Unfortunately, locally hosted LLM or AI services are not compatible with Cursor, as Cursor's backend needs to be able to communicate with the endpoint you choose.

As a workaround, you can expose your localhost endpoint externally, so that Cursor can get to it, but I'd only recommend this if you can do this safely and securely!
