### ISSUE TITLE
Server Memory Utilization 100%

### ISSUE THREAD

**Issue by JackyGohSG** [getcursor/cursor#2352]
I'm running cursor on my Digital Ocean server, and i constantly get alerts on memory utilization at 100%. What could be the cause and how can I troubleshoot this? I have attached my htop screenshot.

Server:
Ubuntu 20.0.4 LTS

![image](https://github.com/user-attachments/assets/78ab331c-e69c-4be5-ac1a-21fc8bc65e7f)

**Comment by wys-evan** [comment]
I had a similar problem

**Comment by JackyGohSG** [comment]
@danperks saw that you help with issues, mind helping some bros out here? :)

**Comment by danperks** [comment]
When you say you are "running" on your server, do you mean you are running Cursor locally, and you are connecting to that server within Cursor, or are you running a whole VM in Digital Ocean, which is running Cursor itself?

I'm assuming the former, and if so, how are you connecting (ssh, tunnels, ect..)

**Comment by JackyGohSG** [comment]
Thanks for the fast response @danperks. In my case, i'm connecting to the server within Cursor through SSH

**Comment by danperks** [comment]
Hey,

We don't do much out of the ordinary with the SSH server, but there are a bunch of reports that this may be caused by a bad extension trying (and probably failing) to run on your server. 

Can you confirm this still happens if you remove any extensions running on the SSH server (should be done in the extensions panel, as it differentiates extensions running on your PC vs the SSH server)?

**Comment by JackyGohSG** [comment]
@danperks i think i found out the reason why. its not an extension issue. but its when i try to SSH into the server root folder, it starts to take up ram. Could be due to cursor filewatcher or something?

This issue is resolved when I go into my projects folder.

**Comment by JackyGohSG** [comment]
thanks @danperks! I shall proceed to close this now.

Solution: Don't use cursor to open your server root folder

**Comment by Yiin** [comment]
I don't agree that it is the best solution, I'd much rather prefer having a configuration option to choose what folders to watch or ignore. Currently I open a folder that contains multiple projects because sometimes I have to take a look at some of them and it's the usage of ram is killing my workflow to the point where I'm considering moving back to vscode for this project.

**Comment by JackyGohSG** [comment]
@Yiin perhaps there is a configuration that we could set within Cursor? I'm not sure about it since I just started using Cursor recently. The beauty of Cursor is it allows you to "speak" to your codebase which requires watching.
