### ISSUE TITLE
[future]Whether it will be made into a plugin

### ISSUE THREAD

**Issue by MHao008** [getcursor/cursor#336]
Whether inheritance to other IDEs will be supported？eg：IntelliJ IDEA

**Comment by pmorange** [comment]
second that, would be nice to see it integrated inside VSCode for instance,.

**Comment by danperks** [comment]
This has been mentioned a few times, but due to the Cursor team's plans for the app's future, an extension would be too limiting in its access to the IDE. Cursor v0.2.0 and up is now based on VSCodium, so it's only a small jump from VSCode to Cursor now, where most extensions should still function as you may expect (you may have to install them manually, see #489's instructions). 

I'll close this issue for now, but if you have any features you think are missing from Cursor, feel free to open a new issue and we'll check it out! 😄
