### ISSUE TITLE
When updating to 2.0, I lost my unsaved contents

### ISSUE THREAD

**Issue by FukoH** [getcursor/cursor#447]
I cannot find where previous files are after updating.Are unsaved contents lost? Some restoring may be needed.

**Comment by Stemmaker** [comment]
You can open the directory you used earlier to save the files, and it may be C:\Users\your_user_name\cursor_tutor in Windows

**Comment by FukoH** [comment]
> You can open the directory you used earlier to save the files, and it may be C:\Users\your_user_name\cursor_tutor in Windows

The files are still there,but contents are lost

**Comment by danperks** [comment]
Cursor should only update when you close the app, and if you choose not to save your files before that, Cursor won't try and save them as it will assume you no longer want them. If you've seen something different, let us know what happened when you updated and what was lost in the process.

**Comment by FukoH** [comment]
> Cursor should only update when you close the app, and if you choose not to save your files before that, Cursor won't try and save them as it will assume you no longer want them. If you've seen something different, let us know what happened when you updated and what was lost in the process.

I just hold a wrong expectation that it may act like SublimeText do.I thought unsaved contents would have been stashed, or at least cursor would prompt something to warn me that the contents are about to lost. In the future other users may encounter similar problem.

**Comment by danperks** [comment]
Usually, if it is closed unexpectedly, Cursor should remember your changes so that when you reopen the folder, it shows your unsaved changes to save or dispose of. Not sure why this may not have happened to you; apologies if you lost any important work!

The change to v0.2.0 was a significant one, so it's likely that unsaved changes between that update would be lost, as the whole underlying codebase was swapped for a new one. The latest version should behave as I described earlier.

**Comment by danperks** [comment]
I'll close this to keep the issues clean, but feel free to comment and we can reopen this.
