### ISSUE TITLE
最新0.2.0变成vscode套了个壳了，基本上和vscode + plugin没啥区别了

### ISSUE THREAD

**Issue by arhatcn** [getcursor/cursor#465]
然后20美金买chatgpt？或者可以用自己的

**Comment by danperks** [comment]
While it is based on VSCodium, the open-source project VSCode is based on, there are a lot of plans for the future that will separate Cursor from VSCode. The integration of AI into the IDE will get much deeper over time, as this is still very much in development. 

Due to how plugins are developed, the plans for Cursor would not be possible within a VSCode plugin, but I understand that, for the moment, it may look like it's just a clone of VSCode. 

Watch this space, as the gap between the two software will only grow from here on out! :smile:

**Comment by sisrfeng** [comment]
> VSCodium, the open-source project VSCode is based on.
![image](https://user-images.githubusercontent.com/53520949/231973410-8bed3d25-7afd-442e-b099-e6fdb7498088.png)
