### ISSUE TITLE
I need to be able to customize the installation location of plugins

### ISSUE THREAD

**Issue by gavinwang668** [getcursor/cursor#478]
希望插件能像VSCODE一样，自定义位置，太多软件都默认安装在win的C盘，C盘经常爆满

**Comment by gavinwang668** [comment]
I need to be able to customize the installation location of plugins because there is not enough space on the default path.

**Comment by danperks** [comment]
While not supported directly in either VSCode, VSCodium or Cursor, it seems there are a few unofficial hacks you can use to move the extension installs to another place:

https://stackoverflow.com/questions/40080793/is-there-a-way-to-change-the-extensions-folder-location-for-visual-studio-code

Closed due to lack of official support for this feature.

**Comment by sisrfeng** [comment]
Location:   C:\Users\YOUR_name______\.cursor\extensions
