### ISSUE TITLE
can provide a plugin for idea

### ISSUE THREAD

**Issue by liliBestCoder** [getcursor/cursor#540]
today i found cursor from wechat official public article, it's amazing to generate code by cursor.but i feel cursor's ide is week than idea.
so can you provide a plugin for idea?

**Comment by truell20** [comment]
Appreciate you reaching out! What features do you miss most about IDEA when you use Cursor?

We're pretty committed to working on our own editor. Most of our planned features aren't possible as plugins.

**Comment by manumartin** [comment]
Pycharm is much better in general and noticeably faster in my experience. I feel conflicted because I love your AI features but I have been forced to switch to an inferior IDE just to use them. Just the simple act of moving the cursor around in vscode is painful, it's noticeably smother and faster in pycharm. Pycharm understands the python code better, for example the structural selection which is a basic feature of pycharm from years ago doesn't work well in vscode. The git support is way inferior unless you pay for the commercial extension. Some plugins that are basic for me like the vim plugin or the "ace jump" plugin are considerably better in pycharm. I could give you a long list of reasons why I prefer Pycharm over VSCODE. I think you should consider working on a pycharm extension and even on one designed to work on a vim environment. Jetbrains is planning on doing something similar to what you are doing as a native feature on their IDEs.

**Comment by ConstasJ** [comment]
I think you can decelop your ide based on IntelliJ platform

**Comment by itzhoujun** [comment]
java boy need jetbrain plugin

**Comment by amal** [comment]
@truell20 it’s a VSCode that just sucks for a lot of developers for a whole bunch of reasons.  You could package any feature in your own IDE based on the IDEA Community edition and get all those developers instantly.  With even a limited set of features as an IDEA plugin, you’d get all e.g. Android developers and others who’re used to specific targeted IDEs.

For instance, all Android development is tightly linked to the Android Studio - an estimated six million developers who can’t just switch to VSCode (too much functionality is tied to the Android Studio).

**Comment by thibaud57** [comment]
Guys really need a plugin please.
Overall design of ideas is better than vscode.
For me the runner is very important. 
I'm struggling by using karma and other stuff for unit test.
Git integration way more better on idea.

**Comment by pf666nb** [comment]
vscode's support for springboot is too limited. If cursor can have an idea plug-in, I will definitely fall in love with it.

**Comment by pf666nb** [comment]
I noticed that there is currently a plug-in that opens the cursor from idea, which can alleviate my needs.
https://plugins.jetbrains.com/plugin/26206-open-in-cursor

**Comment by tompaz3** [comment]
> We're pretty committed to working on our own editor. Most of our planned features aren't possible as plugins.

I would personally prefer limited set of features inside JetBrains IDE rather than all Cursor features in VS Code-based IDE.

**Comment by jintaiyong** [comment]
JetBrains IDE's development experience is much good rather than VSCode, VSCode bad~~ bad ~~ bad~~, need plugin for IDE
