### ISSUE TITLE
Why is the token limit 150k?

### ISSUE THREAD

**Issue by paperkaiser** [getcursor/cursor#618]
May I ask how you set this 150k? Isn't it 150k questions? Why did I run out in one night?

**Comment by danperks** [comment]
Cursor's AI works on "tokens" as with most AI-related stuff. A token is usually a word or part of a word. This is because an AI request gets more expensive and slower the more tokens it contains. Therefore, Cursor's 150k limit if for tokens. When working in large codebases, this can be used up very quickly, so I'd recommend selecting only the relevant sections of code and asking for code changes like that.

**Comment by truell20** [comment]
Tokens measure how much data is sent to the AI in addition to how much data the AI outputs. 

10-20 tokens are about one line of code. 2-3 tokens are about a word.

Each request to the AI will consume a maximum of 4k tokens for 3.5 and 8k tokens for 4. With pro, you're allowed unlimited tokens for 3.5. However, with GPT-4, you can use 150k tokens. After that, you can keep using more, but it's billed on a usage basis. This is to cover our costs, since OpenAI charges us on a per token basis.
