### ISSUE TITLE
编辑器字体大小如何更改？

### ISSUE THREAD

**Issue by pax200409** [getcursor/cursor#621]

**Comment by truell20** [comment]
Since Cursor is a fork of VSCode, you should be able to use the VSCode font size tutorials: https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2022

由于 Cursor 是 VSCode 的一个分支，您应该能够使用 VSCode 字体大小教程：https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors- in-visual-studio?view=vs-2022

**Comment by pax200409** [comment]
cursor里面没有工具选项，命令选项里也没有
