### ISSUE TITLE
Requesting Release Notes

### ISSUE THREAD

**Issue by dallenpyrah** [getcursor/cursor#639]
I would love if you guys started incorporating release notes into your deployment process, it is hard to know what is being added to the application and I would love to share with my friends and people at work. 

If you guys had release notes I could easily pinpoint new exciting features to tell my coworkers about.

**Comment by arvid220u** [comment]
Thanks for the note! We just made pushing to https://changelog.cursor.sh mandatory in our release script so now you should see release notes for every release :)

**Comment by dallenpyrah** [comment]
@arvid220u amazing thank you!

**Comment by soorya-sudha** [comment]
Hi Team
Although this issue is closed, I wanted to ask for some clarification regarding the patch releases.:
I found the change log above very helpful, thank you! I was just wondering about the patch releases.
For example, I’m using Version: 0.45.10 and VSCode Version: 1.96.2, but I couldn't find the change log related to the patch version. I’m curious to know what each release signifies and how it relates to the changes.
