### ISSUE TITLE
Can't connect to private GitHub repo in organisation

### ISSUE THREAD

**Issue by adamski** [getcursor/cursor#649]
I can't add my private GitHub repository that's in an organisation, in order to index the whole codebase. 

The 'Add Repository' button does nothing. Public repos seem to be fine.

**Comment by adamski** [comment]
I changed my mirror to a private repo in my personal GitHub account and it works. So I guess it's an issue with organisation repos.

**Comment by Sanger2000** [comment]
Oh interesting. Could you try logging out and logging back in from GitHub on Cursor? To do so, press this button:
<img width="629" alt="Screen Shot 2023-06-17 at 4 50 42 PM" src="https://github.com/getcursor/cursor/assets/17725268/b699df7f-87f1-44ec-b6fc-9d8fd8756c01">

Then press "connect GitHub" again.

Then when brought to this screen, you need to grant credentials to the org whose private repo you need to index:

<img width="415" alt="Screen Shot 2023-06-17 at 4 48 18 PM" src="https://github.com/getcursor/cursor/assets/17725268/a4366795-3aad-4ca7-bf0e-b2a626493ddc">

For example, in this case, I would need to grant access to "getcursor" in order to index any private repositories in getcursor/ 

My guess is that because the UI isn't very clear, the cursor org wasn't granted access to the org's repos.

**Comment by truell20** [comment]
Just checking here @adamski
