### ISSUE TITLE
it is not free for "monthly"

### ISSUE THREAD

**Issue by leafgrey** [getcursor/cursor#671]
fast requests quota is not count by month ，it is by all time

i did not ask any question at month 7，the number of count is 13，when i ask a question，the number is 14 now，
so the pro is same？

could u check it for the account of “zghnzch@163.com” ？

**Comment by arvid220u** [comment]
Hi! The pro plan has 500 fast requests **per month**.

The free plan has 50 fast requests in total.

Does that make sense?

**Comment by truell20** [comment]
Also, not relevant to the free plan gpt-4 quota, but in general our monthly quotas are not by calendar month. Instead, they counted every 30 days after your start date. Please let us know if you have any more questions here!

**Comment by leafgrey** [comment]
> Also, not relevant to the free plan gpt-4 quota, but in general our monthly quotas are not by calendar month. Instead, they counted every 30 days after your start date. Please let us know if you have any more questions here!

this make sense

**Comment by Thisdudehoaluu** [comment]
Hello Michael Truell,

Is there any chance I can be removed from the email list? until I am ready
to understand the emails. Because currently I receive it as spam and have
not been able to read it.

Again please remove me from your mailing list. Until I am ready to read the
coding terminology, I would like to be clear from the emails.

Please and thank you,
--Hoa Luu
