### ISSUE TITLE
A server error has occurred

### ISSUE THREAD

**Issue by Meng0-deep** [getcursor/cursor#70]
Here's the thing: I copy a bunch of data from an excel spreadsheet into the software, I want it to output the code as I want, and then I try to change some of the content of the code above, and it gives an error
事情是这样的：我将excel表格中的 一堆数据复制到软件里，然后按我的想法让它输出代码，然后我接着想更改一些上边代码的内容，它就报错了

**Comment by AimengyangGG** [comment]
经过我的努力，它再一次发生了！

**Comment by truell20** [comment]
Do you still get an error? Could you paste in your prompt here?

**Comment by szfmsmdx** [comment]
> Do you still get an error? Could you paste in your prompt here?


I get this problem now, when i want to use cursor to generate a functional module design description of the system, then the error appear, here is the error screen capture, I would appreciate it if you could help me.

![error_pic](https://user-images.githubusercontent.com/84652873/227089296-66d20e20-9026-4994-83f6-5fecbb2bdd4e.png)

**Comment by AimengyangGG** [comment]
I remember that if the operation is repeated, it will be executed, it will report an error, and then it will be executed after the operation.



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 23, 2023 11:05 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [getcursor/cursor] A server error has occurred (Issue #70)




  
Do you still get an error? Could you paste in your prompt here?
  
I get this problem now, when i want to use cursor to generate a functional module design description of the system, then the error appear, here is the error screen capture, I would appreciate it if you could help me.

**Comment by szfmsmdx** [comment]
> I remember that if the operation is repeated, it will be executed, it will report an error, and then it will be executed after the operation.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Mar 23, 2023 11:05 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [getcursor/cursor] A server error has occurred (Issue #70) Do you still get an error? Could you paste in your prompt here? I get this problem now, when i want to use cursor to generate a functional module design description of the system, then the error appear, here is the error screen capture, I would appreciate it if you could help me. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Thanks for your response, I'll go back and try again. ^ ^

**Comment by AimengyangGG** [comment]
It's my pleasure to help you.



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 23, 2023 11:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [getcursor/cursor] A server error has occurred (Issue #70)




  
I remember that if the operation is repeated, it will be executed, it will report an error, and then it will be executed after the operation.
 …
 ---Original--- From: @.&gt; Date: Thu, Mar 23, 2023 11:05 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [getcursor/cursor] A server error has occurred (Issue #70) Do you still get an error? Could you paste in your prompt here? I get this problem now, when i want to use cursor to generate a functional module design description of the system, then the error appear, here is the error screen capture, I would appreciate it if you could help me. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Thanks for your response, I'll go back and try again. ^ ^

**Comment by xiaopange** [comment]
<img width="663" alt="error" src="https://user-images.githubusercontent.com/24327140/228109519-f08e8fc6-8f79-419e-8c7b-6c85c6de0369.png">
Please tell me how to do it，I just want to create a button

**Comment by Meng0-deep** [comment]
For me, I just turn off the error prompt and repeat the operation.



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 28, 2023 10:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [getcursor/cursor] A server error has occurred (Issue #70)




 

 Please tell me how to do it，I just want to create a button

**Comment by truell20** [comment]
Should be fixed in newest version 🙂
