### ISSUE TITLE
Disable the "Ctrl+L to chat, Ctrl+K to Generate" Hint (not the popup)

### ISSUE THREAD

**Issue by marcelo-mason** [getcursor/cursor#744]
**Is your feature request related to a problem? Please describe.**
"Ctrl+L to chat, Ctrl+K to Generate" hint when clicking a new line is visible at nearly all times while editing code, once you have the shortcuts memorized it just becomes an annoyance.

**Describe the solution you'd like**
Ability to disable it via settings

**Additional context**
I don't mean the popup, which can already be disabled in settings:
![image](https://github.com/getcursor/cursor/assets/577340/62bf230f-7d45-4479-990c-9090128d5dcb)

I mean the Hint, present in all empty lines, and visible at nearly all times while editing code:
![image](https://github.com/getcursor/cursor/assets/577340/4d6aa52e-efe5-4c59-99f1-93386de4b319)

**Comment by jakobFNF** [comment]
Disabling the Chat/Edit Tooltip will also remove the hint text.

![image](https://github.com/getcursor/cursor/assets/74077124/6333a8d8-f101-444d-a5f0-c2f6b08265c4)

**Comment by lakesare** [comment]
I want the Chat/Edit Tooltip, but absolutely don't want the "Ctrl+L to chat, Ctrl+K to Generate" comment. I'd like an option for that.

**Comment by Korolen** [comment]
> I want the Chat/Edit Tooltip, but absolutely don't want the "Ctrl+L to chat, Ctrl+K to Generate" comment. I'd like an option for that.

Same. It's weird how much it distracts my mind. It's just *floating there*, popping in and out & hanging out, over + on top of all my code, in its own frontal layer; inkillably ... but only sometimes, it goes in and out depending on if you're selecting, just to make sure you're noticing it ... argh!

I'm positive I can adjust my mind and get used to it, but, I'm documenting my initial reaction here just since it can't be uncommon, and I feel there absolutely must be a setting for this!

Some of us hate clutter when we're trying to focus!

(Frustratingly, I can't manually remove it like I normally would. On the web, I'd just Cmd+Alt+C Select and Inspect Element, and add some User CSS to hide it based on a css selector. In VSCode, there's Developer: Open Webview Developer Tools, but for some reason the Select and Inspect function hotkey doesn't work, and when I physically click the button for it in the top left of the devtools pane, the focus changes and the popup hides every time! So I can't select it to get its class/id! Argh! :P -.- It skirts my wrath with perfect mastery of 'the dodge'! It will not be destroyed! 😏 hahaha)

**Comment by dep** [comment]
I don't see the `Chat/Edit Tooltip` option:

![CleanShot 2024-04-02 at 10 18 43](https://github.com/getcursor/cursor/assets/55112925/78bf2f7a-cf91-4f55-82cf-21139c66b5c1)

**Comment by dep** [comment]
Ahh I found it in the app's actual settings, not to be confused with the user settings:

![CleanShot 2024-04-02 at 10 26 03](https://github.com/getcursor/cursor/assets/55112925/9494a5dc-7bba-413b-9ed3-d5a7cc145f5d)

**Comment by subproject22** [comment]
Tooltip option is brain dead trash and should be removed from defaults.

**Comment by eriknaslund** [comment]
I can't find this in Cursor 1.0. Has the setting moved again? The ctrl+l ctrl+k reminder hint is INCREDIBLY annoying!!

**Comment by hazouka** [comment]
Turning This Off Will take it off

![Image](https://github.com/user-attachments/assets/f5fd9504-7104-4985-975e-7a076692c505)

**Comment by dalmotix** [comment]
The original issue described here hasn't been fixed. We need a separate toggle for the hint that pops up over an empty line than the toggle for the selection popover.

**Comment by hiandy24** [comment]
in cursor2, you can go to cursor setting and agent -> inlienediting & terminal, turn off the terminal hint. You can still use the ctrl + K to generate shell script, but no hint in the bottom. This hint is total shit for minimal user like me.
