### ISSUE TITLE
Please rename the project, it's almost impossible to google it

### ISSUE THREAD

**Issue by flutterrausch** [getcursor/cursor#850]
Really. Thanks.

**Comment by flutterrausch** [comment]
9 results (altogether)..

Try to google how many gpt-4 uses are left.

**Comment by truell20** [comment]
A little late at this point to make a name change :/

**Comment by oreganmike** [comment]
A total rebrand overhaul seems a little drastic. It is challenging to hone in on Cursor content, i'd agree. Especially when the product name is referenced as a mouse (cursor) in like a bazillion support and troubleshooting articles for every product, ever. 
There's also cursor.sh and cursor.so kicking about, where only cursor.sh contains the forum. 
I get it's all new 'n' stuff. Maybe something to bear in mind.

**Comment by sualehasif** [comment]
yaaaa, it is a bit late to rename. feel free to reopen the issue with ideas about how we can make certain things more visible. is this about tutorials/videos or documentation or something else.

**Comment by rannyeribaptist** [comment]
Maybe just add "code editor" after the name "cursor". If I ever have to research about anything related to it I can just put "how to XYZ on cursor code editor".

**Comment by oreganmike** [comment]
Sure, you *can*. The point is, it's harder than it needs to be. 
I did a few quick tests trying to search google for posts from forum.cursor.sh, and despite using the posts' titles they were nowhere to be seen on the first page of results. 

So i had a look at both cursor.so and cursor.sh (ignoring the million dollar question of why there's two domains):
- Name servers: cursor.so is using registrar-servers.com while cursor.sh is using AWS. Not a huge deal wrt SEO, just confusing really.
- CNAME records: there's no cname record aliasing cursor.so and cursor.sh. This may be intentional, though not sure why. 
- TXT records: cursor.so has Google site verification TXT records, which is good for SEO.
- TXT records: cursor.sh on the other hand doesn't, and it hosts your forum. Which may be the reason why only forum.cursor.sh is returned but posts from the site are really hard to find. 

If you've got google analytics enabeld, check to see where your referrer traffic comes from. I'd hazard a guess the majority comes from the 'Forum' link on your cursor.so homepage (and not google).

**Comment by vasco3** [comment]
rename it to VS Cursor
