### ISSUE TITLE
Allow Setting Cursor as Default Editor in Github Desktop

### ISSUE THREAD

**Issue by HelloAlexPan** [getcursor/cursor#900]
I use GH Desktop for as my desktop git client. In DH Desktop settings, you can specify the default external editor to open a repo in...

<img width="500" alt="image" src="https://github.com/getcursor/cursor/assets/53453555/24d14117-8521-4ba1-b5d6-64927f817a91">

... but you cannot select Cursor as an option:

<img width="500" alt="image" src="https://github.com/getcursor/cursor/assets/53453555/9d4cf676-635e-4205-b951-c4b6258c0f4e">

It would be good to allow for Cursor to be selected as a default external editor in GH Desktop. 

The Cursor team would have to file a PR to the GH Desktop team [to modify this file](https://github.com/desktop/desktop/blob/a1ece186bae3a742f206c5edeb0762e78fba2f7c/docs/technical/editor-integration.md?plain=1#L240)

**Comment by JWegener** [comment]
I want this too!

**Comment by oliverpitsch** [comment]
+1

**Comment by Willaiem** [comment]
I've found the "workaround", which sadly needs the VS Code, but otherwise, it won't work:

- Go to `C:\Program Files\Microsoft VS Code\bin` and edit the `code.bat` file
- Change the next-to-last line 

from:
`"%~dp0..\Code.exe" "%~dp0..\resources\app\out\cli.js" --ms-enable-electron-run-as-node %*`

to:
`"C:\Users\yamnik\AppData\Local\Programs\cursor\Cursor.exe" "%~dp0..\resources\app\out\cli.js" --ms-enable-electron-run-as-node %*`

and now GitHub Desktop will open the Cursor instead of VS Code.

Kinda a hacky solution, but works.

**Comment by BlocBoiMonzer** [comment]
+100 totally agree or simply allow for people to add a filepath to the program we want to open no matter how new or unknown it is!

**Comment by ryanmio** [comment]
+1

**Comment by oliverpitsch** [comment]
Just found out by accident that this now works. I'm using Github Desktop 3.3.5 here, but [it was already added in 3.3.4](https://github.com/desktop/desktop/issues/17462)
![image](https://github.com/getcursor/cursor/assets/2378512/a96090cf-717f-41fc-8060-81f06aab9db8)

**Comment by n13** [comment]
I searched the internet and came here, and read all of this tried to update GH Desktop, still nothing. 

Then I realized I haven't restarted GH Desktop in months .. its always running. 

Restarted and Cursor appeared. 

So after installing Cursor, restart GH Desktop so it can pick up on that new IDE.

**Comment by n13** [comment]
> This worked for me with a small change:
> 
> instead of `"C:\Users\<your-username>\AppData\Local\Programs\cursor\Cursor.exe" "%~dp0..\resources\app\out\cli.js" --ms-enable-electron-run-as-node %*`
> ....
You really don't need to do this, update VS Code and restart it, then you will see cursor as one of the options for editor.

**Comment by GUIMess** [comment]
> > This worked for me with a small change:
> > instead of `"C:\Users\<your-username>\AppData\Local\Programs\cursor\Cursor.exe" "%~dp0..\resources\app\out\cli.js" --ms-enable-electron-run-as-node %*`
> > ....
> 
> You really don't need to do this, update Github Desktop and restart it, then you will see cursor as one of the options for editor.

It really hasn't been updated on windows. If you have it working, you are somehow the exception, not the rule.

**Comment by alfulinku** [comment]
> > > This worked for me with a small change:
> > > instead of `"C:\Users\<your-username>\AppData\Local\Programs\cursor\Cursor.exe" "%~dp0..\resources\app\out\cli.js" --ms-enable-electron-run-as-node %*`
> > > ....
> > 
> > 
> > You really don't need to do this, update Github Desktop and restart it, then you will see cursor as one of the options for editor.
> 
> It really hasn't been updated on windows. If you have it working, you are somehow the exception, not the rule.

Yes I tried reinstallint and rebooting but I can't see cursor in the list somehow

**Comment by Krashnicov** [comment]
+1 for this.

**Comment by kevin207** [comment]
Any updates on this?

**Comment by manojpgoswamigit** [comment]
It still does not work on the Windows version out of the box, **HOWEVER** I can confirm this workaround works just fine on 24 June 2024 with both the current beta(v3.4.2-beta3) and stable(v3.4.1).

* Go to `C:\Program Files\Microsoft VS Code\bin` and edit the `code.bat` or 'code.cmd' file
![image](https://github.com/getcursor/cursor/assets/108041815/3e6cecce-8baa-482f-bd94-ca28945e5e78)

* Change the line to this (don't forget to put your username in the line)
**Instead of :**
"%~dp0..\Code.exe" "%~dp0..\resources\app\out\cli.js" --ms-enable-electron-run-as-node %*

**Use this :**
"C:\Users\<your-username>\AppData\Local\Programs\cursor\Cursor.exe" "%~dp0..\resources\app\out\cli.js" %*
![image](https://github.com/getcursor/cursor/assets/108041815/f0885159-d359-4015-9990-65b87b4f36bd)

Now using "Open in Visual Studio Code" button will launch in Cursor instead.(ignore the button label)
![image](https://github.com/getcursor/cursor/assets/108041815/84a91fb0-1f5f-467f-822a-bafa970aaec4)

**Comment by beyondthecode-bc** [comment]
@alfulinku with @manojpgoswamigit update works for me - **Update - 4th of July**

**Comment by colinabear** [comment]
For anyone curious: I made a PR to add windows support, but there's also a sweet new feature coming up to allow you to set a custom IDE: https://github.com/desktop/desktop/pull/18954

Either way, Windows bros should be officially supported soon 🙏

**Comment by chadallard** [comment]
I had issues with Cursor appearing on both Mac and PC. On Mac, a simple restart of the app did the trick but I couldn't get it to show up on PC.

I had tried many of the above workarounds but they either didn't work or seemed too "hacky" to me.

I did have the latest version update and had restarted my PC, and so forth to no avail.

What ultimately worked was reinstalling GitHub Desktop. From that point forward, Cursor appeared. So if you have the latest version and still can't see Cursor as an option on PC, you may need to reinstall it for it to show up.

**Comment by JEuler** [comment]
After recent Cursor Windows problems with update - it is disapeared for me in this menu
