### ISSUE TITLE
Updates and Remote-SSH Failures (Workaround)

### ISSUE THREAD

**Issue by jamesneal** [getcursor/cursor#959]
This is kind of a "meta ticket", to help people when Remote SSH connections break after an update.

The issue happens when you have multiple Cursor Remote SSH connections to the same server.  After a client update, each of these windows will immediately connect to the server and attempt an upgrade.  They each try to write to the same file, which results in a corrupted tarball.

The fix is to login to your remote server, and `rm -rf $HOME/.cursor-server/bin`

Next time you connect to that host, it'll go through the steps to reinstall the server, and-- hopefully-- succeed.

**Comment by truell20** [comment]
Thank you for posting this :) Should have a systematic fix for this in the next release

**Comment by jayhickey** [comment]
@truell20 can y'all fix the remote ssh server script link in the meantime? Connecting to a remote host with ssh is completely broken right now because the script link at https://cursor.blob.core.windows.net/remote-releases/0.12.1-e828afa25b30c59e602dba98c5060e2f1d552120/vscode-reh-win32-x64.tar.gz does not exist.

See #915 for more context

**Comment by truell20** [comment]
Closing because the multiple connection race is fixed I believe
