### ISSUE TITLE
Cursor version is not compatible for some extensions

### ISSUE THREAD

**Issue by mohamedd-musstafa** [getcursor/cursor#993]
Cannot download some extensions because the cursor version is not compatible (not supported), even though that extension is released in 2023 and is not an old extension.

**Comment by jakobFNF** [comment]
An update for this should drop today or tomorrow morning. The team is working really hard on it. Thank you for your patience!

**Comment by jakobFNF** [comment]
This update will begin rolling out to users slowly in a few hours. That means we release it to a few randomly selected users first before making it available to everyone. Since this update carries a higher risk of bugs, it might take an additional ~12 hours before everyone receives it. Thank you for your patience!

**Comment by jakobFNF** [comment]
A staged rollout for the VS Code version update (0.13.0) has started. You can also redownload from https://cursor.sh/ to instantly get the latest version (all of your settings/extensions will move over to the redownloaded version).
