### ISSUE TITLE
Code Version bump to ^1.82.0 for supporting Volar Extension

### ISSUE THREAD

**Issue by mike1936** [getcursor/cursor#997]
Hi, I am new to cursor from vscode. Some of the imported extensions are not working after switching to cursor. The most important one is for providing the Vue 3 language support as mentioned in title, `Vue.volar` is its identifier.

And after installing the extension it was grayed out, saying `Extension is not compatible with Code 1.80.1. Extension requires: ^1.82.0.`, would there be any recent plan for the team to upgrade the code backend?

**Comment by jonny-ras** [comment]
I've managed to make it work by going back a few versions on the vue extension. It'd be great to get to the most recent version though 👍

**Comment by jakobFNF** [comment]
An update for this should drop today or tomorrow morning. The team is working really hard on it. Thank you for your patience!

**Comment by jakobFNF** [comment]
This update will begin rolling out to users slowly in a few hours. That means we release it to a few randomly selected users first before making it available to everyone. Since this update carries a higher risk of bugs, it might take an additional ~12 hours before everyone receives it. Thank you for your patience!

**Comment by jakobFNF** [comment]
The staged rollout has started. You can also redownload from https://cursor.sh/ to instantly get the latest version (all of your settings/extensions will move over to the redownloaded version).
